(define (factorial n)
  (define (butler product counter)
    (if (= counter 1)
        product
        (butler (* product (- counter 1)) (- counter 1))
        )
    )
  (if (not (and (>= n 1) (integer? n)))
      (display "that ain't no integer beeeyotch!!\n")
      (butler n n)
      )
  )

(factorial 4)
(factorial -2.309)
(factorial 0)

(define (downfac m)
  (cond ((= m 0) 0)
        ((= m 1) 1)
        ((and (integer? m) (> m 0))
         (* m (downfac (- m 1)))
         )
         (else (display "t'aint a number I can do\n"))
         )
        )

(downfac 4)
(downfac -.3904)