(define (factorial n)
  
  (define (butler product counter max-count)
    (cond ((= max-count 0) 1)
          ((> counter max-count) product)
          (else (butler (* product counter) (+ counter 1) max-count))
        )
    )
  (if (and (integer? n) (> n 0))
  (butler 1 1 n)
  "I pity the foo that tries to factorialize non-integers!"
  )
  )

(define (n-power n)
  (define (butler product counter max-count)
    (if (> counter (abs max-count))
        product
        (butler (* product max-count) (+ counter 1) max-count)
        )
    )
  (butler 1 1 n)
  )

(define (fact-vs-fiction k)
  (define (butler counter max-count)
  (if (> counter max-count)
      (display "^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ \n Good luck avoiding the spike strip.")
      (begin (display (factorial counter))
             (display "  ")
             (display (n-power counter))
             (display "\n")
             (butler (+ counter 1) max-count)
             )
      )
    )
  (butler 0 k)
  )

(fact-vs-fiction 25)
